FROM python:latest

ENV PYTHONUNBUFFERED 1

ADD ./web /src

WORKDIR /src
ENV PYTHONPATH=/src

RUN pip install -r requirements.txt

EXPOSE 80

CMD uwsgi --socket 0.0.0.0:80 --protocol=http -w server:app